trendmicro/cloudone-filestorage-plugins

post-scan-actions/aws-python-promote-or-quarantine/README.md

If the tagging lambda deployed by Storage Stack finishes first, this promote-or-quarantine lambda will fail with an access denied error.

fix: Add tagging actions in example IAM policy

---

post-scan-actions/aws-python-promote-or-quarantine/README.md

- When copying the JSON string of the custom policy on AWS web console, it shows an error message `JSON strings must not have leading spaces.`.
- So I remove the leading spaces in README.rd

docs: Remove leading whitespaces in JSON code section about the custom policy

---

post-scan-actions/aws-python-promote-or-quarantine/README.md

docs: Latest versions of the AWS CLI requires the --protocol flag for an 'sns subscribe' command.

docs: Add missing flag to SNS subscribe command

---

post-scan-actions/aws-python-promote-or-quarantine/README.md
post-scan-actions/aws-python-promote-or-quarantine/handler.py

Greetings,
Our usage of `aws-python-promote-or-quarantine` plugin has revealed some corner-cases that required slight modification to `handler.py` as well as the custom lambda execution policy (`YOUR_FSS_LAMBDA_POLICY`). Specifically, we have a source bucket with strict deny rules and have object replication configured on our promotion bucket. To get this plugin working we had to make two modifications:
- add the `s3:PutObjectAcl` action to the custom lambda exection policy
-  include the `ACL` parameter to the `copy_object` function (with a value of `bucket-owner-full-control` in our case)
I've not modified the current 'default' behavior of `handler.py` (though I did do some refactoring) but instead added environment variables which change the runtime behavior. If a user were to follow …

feat: add optional lambda environment variables

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

Since SAR doesn't provide dropdown list for parameter options like the CloudFormation console, we should add the options in the description.
Result on SAR/Lambda console:

docs: Add options of parameters in description for SAR

---

post-scan-actions/aws-nodejs-securityhub-integration/README.md
post-scan-actions/aws-nodejs-securityhub-integration/lambda/index.js
post-scan-actions/aws-nodejs-securityhub-integration/lambda/package-lock.json
post-scan-actions/aws-nodejs-securityhub-integration/lambda/package.json
post-scan-actions/aws-nodejs-securityhub-integration/template.yaml

FSS Product team,
This PR adds a new plugin to the post-scan-plugins repository. The goal of this plugin is to forward all malware detections to SecurityHub, given one is already configured.
I make myself available to work together on having this PR approved.
There are two files:
* `fss-to-security-hub-lambda.zip` Where the NodeJS code lives. It must be uploaded to customer's managed S3 prior to deployment.
* `template.yaml` CloudFormation template that deploys the plugin to customer's environment.
* `snsScanResultTopicArn:`   FSS Results SNS Topic ARN
* `LambdaZipBucket`          S3 bucket for lambda zip. If your have it under s3://bucket/path/to/zip.zip, enter 'bucket' here.
* `LambdaZipKey`             S3 key for lambda zip. If your have it under s3://bucket/path/to/zip.zip, enter …

Adding the capability of pushing events from FSS to SecurityHub.

---

.gitignore
post-scan-actions/aws-python-conformity-custom-check/README.md
post-scan-actions/aws-python-conformity-custom-check/handler.py
post-scan-actions/aws-python-conformity-custom-check/template.yml

This change adds a new post-scan action to publish malicious file details to Trend Micro's Cloud One Conformity product as a Custom Check.
Currently, the conformity custom checks endpoint does not support forward slashes in resource names so the name format for the resource is the S3 URI with forward slashes replaced by colons.
Also support for TTL to auto expire messages has been built into code but commented out in anticipation for a future update to Conformity to allow users to specify TTLs with Custom Checks.
Example custom check when viewed within Conformity:

feat: fss-to-conformity-custom-check

---

post-scan-actions/aws-python-conformity-custom-check/handler.py
post-scan-actions/aws-python-conformity-custom-check/template.yml

Error without this fix and azure subscriptions present:
[ERROR] KeyError: 'awsaccount-id'
Traceback (most recent call last):
File "/var/task/handler.py", line 49, in lambda_handler
ccaccountid = get_cc_accountid(account_id)

fix: conformity-postscan-plugin-account-lookup

---

post-scan-actions/aws-python-conformity-custom-check/handler.py
post-scan-actions/aws-python-conformity-custom-check/template.yml

Fix bucket & fileprefix object when bucket is in region other than us-east-1
Fixes the split to support regions other than us-east-1
Error without this fix:
`[ERROR] IndexError: list index out of range
Traceback (most recent call last):
File "/var/task/handler.py", line 56, in lambda_handler
fileprefix = message["file_url"].split(".s3.amazonaws.com/")[1]
[ERROR] IndexError: list index out of range Traceback (most recent call last):   File "/var/task/handler.py", line 56, in lambda_handler     fileprefix = message["file_url"].split(".s3.amazonaws.com/")[1]`

fix: fss conformity custom check bucketname / path generation

---

post-scan-actions/azure-python-promote-or-quarantine/README.md

Specify worker runtime when publishing Azure function.

docs: Fix command to publish Azure function

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

fix: Remove bucket name constraint to allow dot(.)

---

post-scan-actions/aws-python-conformity-custom-check/README.md

- Modify the instructions on how to create an API Key before installing conformity-custom-check plugin
- fix issue #81 

docs: Fix instructions on how to create conformity API Key

---

cspell.json
post-scan-actions/gcp-python-promote-or-quarantine/Makefile
post-scan-actions/gcp-python-promote-or-quarantine/README.md
post-scan-actions/gcp-python-promote-or-quarantine/docs/deploy-tutorial.md
post-scan-actions/gcp-python-promote-or-quarantine/main.auto.tfvars.example
post-scan-actions/gcp-python-promote-or-quarantine/main.tf
post-scan-actions/gcp-python-promote-or-quarantine/src/main.py
post-scan-actions/gcp-python-promote-or-quarantine/src/requirements.txt
post-scan-actions/gcp-python-promote-or-quarantine/variables.tf

Add GCP promte and quarantine plugin
If open in cloudshell button needed to test use [this link](https://shell.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https%3A%2F%2Fgithub.com%2Fandrew-c-lee%2Fcloudone-filestorage-plugins.git&cloudshell_workspace=post-scan-actions%2Fgcp-python-promote-or-quarantine&cloudshell_tutorial=docs/deploy-tutorial.md)

feat: Add GCP Promote and Quarantine Plugin

---

post-scan-actions/gcp-python-promote-or-quarantine/README.md
post-scan-actions/gcp-python-promote-or-quarantine/main.auto.tfvars.example
post-scan-actions/gcp-python-promote-or-quarantine/main.tf
post-scan-actions/gcp-python-promote-or-quarantine/variables.tf

* Lock to terraform GCP version to `4.0.0`
* Extract `project_id`, `region` and `plugin_prefix` from `project_settings` so that the values can be properly set in interactive CLI.
* Add the random suffix to `titles` and `display_name` so the related resource can be more easily distinguish.
* Fix the role binding problem by reference the `name` instead of `role_id` 

fix: fix gcp promote and quarantine role binding failed

---

post-scan-actions/aws-python-email-notification/README.md

Change the following on post-scan-actions/aws-python-email-notification/README.md
- add link to the SES document
- delete steps to take note of Policy ARN because there's no step to use it.
- add steps to copy SNS Topic URL to [Subscribe the Lambda to the SNS topic]>[Using the AWS console] because there's no step to copy ScanResultTopic ARN.
I enhanced this Post Scan Action README where I was a bit confused when utilizing it. 
I'm not very familiar with GitHub, so please point out any mistakes in the commit messages or operations.
Thanks!

docs: minor improvements for README.md

---

post-scan-actions/gcp-python-promote-or-quarantine/variables.tf

Within the file `variables.tf` the variable `function_perfix` is changed to the correct name `plugin_prefix`.

fix: Fix GCP plugin's variable name

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/README.md
scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.json
scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.yaml

The current Full and Scheduled Scan approach is flawed for buckets that have at least thousands of files as it fails to finish scanning before the AWS Lambda Function times out. This PR merges the plugin to use AWS Step Functions in order to get the job done.
Do you want to read about my saga to get this fixed?
[Here](https://awstip.com/how-to-use-and-not-use-aws-step-functions-9fe6a93fa59e) and [here](https://raphabot.medium.com/how-to-hit-aws-step-functions-limitations-b4c413da10e4).

feat: Migrates Full and Scheduled to use AWS Step Functions

---

post-scan-actions/gcp-python-promote-or-quarantine/Makefile
post-scan-actions/gcp-python-promote-or-quarantine/README.md
post-scan-actions/gcp-python-promote-or-quarantine/docs/deploy-tutorial.md
post-scan-actions/gcp-python-promote-or-quarantine/main.tf

Using terraform archive to pack function zip instead of using `make`.

feat: Switch gcp promote quarantine source to terraform archive

---

post-scan-actions/aws-python-conformity-custom-check/handler.py
post-scan-actions/aws-python-conformity-custom-check/template.yml

- Extend the allowed values for the region parameter to the current 9 AWS Cloud One regions.
- Change the API endpoint to the Cloud One instead of the legacy Conformity one.

fix: Add Cloud One Regions and Endpoints

---

deployment/aws-terraform/README.md
deployment/aws-terraform/all-in-one/providers.tf
deployment/aws-terraform/all-in-one/variables.tf

I got few errors when using terraform all in one for AWS, so this PR:
- Fix typo in vars description
- Remove obsolete field in aws provider (make it fails with latest version)
- Fix docs for cleanup (missing region)

fix: Fix AWS terraform all in one

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.yaml

fix: Remove redundant commas in template.yaml

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/README.md

Fix the template file name and add a link to the raw file.

fix: Fix readme of full scheduled scan plugin

---

post-scan-actions/azure-python-promote-or-quarantine/promoteOrQuarantineFunction/ScanResultHandler/handler.py

1. Fix the plugin azure-python-promote-or-quarantine which will misjudge the event about scan failure.

fix: The FSS tags and metadata of scan failure file will change after performing plugin azure-python-promote-or-quarantine

---

.github/workflows/release.yml

I encountered an error ([Bad request](https://github.com/trendmicro/cloudone-filestorage-plugins/actions/runs/5139877791)) in a previous PR that was merged. Upon investigation, I discovered that the error was caused by a restriction on using external actions in the "trendmicro/cloudone-filestorage-plugins" repository.
To address this issue, I reviewed other actions within the Trend Micro organization and found examples that were not restricted, such as [scottbrenner/cfn-lint-action@v2](https://github.com/trendmicro/cloudone-community/blob/6a222480dd33739b4450017c953731b673ee2e28/.github/workflows/linter.yml#LL25C15-L25C46). Based on this information, I updated the action version from `v35.9.2` to `v36` to comply with the error message requirement: `svenstaro/upload-release-action@v*, …

fix: Resolve GitHub Actions restriction in workflow

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.yaml

- There is no `version.json` in the Lambda function in this plugin. So delete code block handling it.

fix: Remove useless code block in aws-python-bucket-full-and-scheduled-scan plugin

---

deployment/aws-terraform/account-scanner-stack/variables.tf
deployment/aws-terraform/all-in-one/variables.tf
deployment/aws-terraform/scanner-stack/variables.tf
deployment/aws-terraform/storage-stack/variables.tf

- The TrendMicroManagementAccount should be string type. Since the account ID has the possibility of beginning with 0.
- Change to type of variable `TrendMicroManagementAccount` in every variables.tf.

Change the type of TrendMicroManagementAccount to string

---

.github/pull_request_template.md
post-scan-actions/azure-python-promote-or-quarantine/template.json

1. Update pull request check list.
2. Update the version in Azure promote or quarantine template file.
- [v] Not required
- [v] Not required
New template deploy the promote or quarantine with the code which enhanced on v1.0.2.
Success to promote a 2.8GB file

chore: Update Azure artifact version and PR template

---

post-scan-actions/azure-python-promote-or-quarantine/README.md
post-scan-actions/azure-python-promote-or-quarantine/template.json
post-scan-actions/azure-python-slack-notification/template.json
post-scan-actions/azure-python-teams-notification/template.json

Azure announced that [they will retire classic Application Insights on 29 February 2024](https://azure.microsoft.com/en-us/updates/we-re-retiring-classic-application-insights-on-29-february-2024/).
- Add a new parameter, `LogAnalyticsWorkspaceResourceID`, to support it.
- Add a new parameter, `VNETRestrictedAccessForAzureMonitorResources`, in `azure-python-promote-or-quarantine` plugin.
- Log Analytics workspaces also provide properties, `publicNetworkAccessForIngestion` and `publicNetworkAccessForQuery`, to configure the network access. We think the Azure Monitor resources, like Application Insights and Log Analytics workspaces, should allow or disallow public network access at the same time.
- When any of `VNETRestrictedAccessForApplicationInsights` and …

feat: Migrate classic Application Insights to workspace-based Application Insights for Azure plugins

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

Fix AWS quarantine plugin template publish error, because SAM's "Fn::Equals" does not support comparing comma delimited parameter.
```
➜  aws-python-promote-or-quarantine git:(master) ✗ sam validate -t packaged.yaml --lint
E8003 Every Fn::Equals object requires a list of 2 string parameters
/Users/jack_c_tang/dev/fss-public/cloudone-filestorage-plugins/post-scan-actions/aws-python-promote-or-quarantine/packaged.yaml:140:9
Error: Linting failed. At least one linting rule was matched to the provided template.
```

fix: AWS quarantine plugin template

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

Remove KMSKeyARNs from Lambda function's env var since it's not necessary. 
Test result:

fix: deploy stack failed because of the kmskey parameter

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

Purpose:
Align the VPC config with the stack template to support connecting multiple subnets with the promote quarantine plugin.
Verify the solution:

fix: make aws promote quarantine template support multiple subnets

---

post-scan-actions/gcp-python-promote-or-quarantine/main.tf

- Update GCP terraform module
- Allow promote and quarantine function to update object in scanning bucket

fix: GCP promote quarantine failed to add tag in scanning bucket

---

post-scan-actions/aws-python-promote-or-quarantine/handler.py
post-scan-actions/aws-python-promote-or-quarantine/template.yml

1. this handler has same code with inner post-action-tag function. Add a starter logging information for helping debug

chore: Add logging statement to aws-python-promote-or-quarantine handler
