post-scan-actions/aws-python-promote-or-quarantine/README.md

Add_GIS_feedback

---

post-scan-actions/aws-python-promote-or-quarantine/Makefile
post-scan-actions/aws-python-promote-or-quarantine/README.md
post-scan-actions/aws-python-promote-or-quarantine/handler.py

-Add 15s sleep timer to quarantine handler.
-Adjust timeout in Makefile to 30s.
-Adjust README to reflect changes above.

fix: allow tagging to occur after scan before move

---

post-scan-actions/aws-python-promote-or-quarantine/README.md

- Update Lambda environmental variables examples.
- Added testing instructions for AWS Console and CLI.
- Specified in testing that move of file is not instant.

docs: clarified readme for quarantine script

---

post-scan-actions/aws-python-promote-or-quarantine/README.md

docs: Updated the aws cli command in line 37 to  "aws iam create-policy --policy-name <YOUR_FSS_LAMBDA_POLICY> --policy-document file://fss-trust-policy.json"

docs: updated line 37 of Readme.md

---

post-scan-actions/aws-python-email-notification/Makefile
post-scan-actions/aws-python-email-notification/README.md
post-scan-actions/aws-python-email-notification/handler.py

feat: send email notification by ses when maleware got detected

Send Email Notification with AWS SES when malware got detected

---

post-scan-actions/aws-python-slack-notification/Makefile
post-scan-actions/aws-python-slack-notification/README.md
post-scan-actions/aws-python-slack-notification/handler.py

Updating PR for the new Slack plugin for FSS

feat: Adding Slack Notification integration with FSS

---

post-scan-actions/aws-python-promote-or-quarantine/README.md

I recently configured the `post-scan-action` plugin via `CLI` and ran into several issues:
- Was not able to create an `IAM` role with the instructed command. A `trust policy` is required so I've added this to step 4 in `CLI - Create an execution role for the Lambda function`.
- Was not able to subscribe to an `SNS` topic via `CLI`. I was able via the `AWS Console` only. It seems there's an additional command required, and so I've added it under step 3 in `CLI - Subscribe the Lambda to the SNS topic`

docs: add missing command and flags to CLI instructions

---

.gitignore
.markdownlintrc
.vscode/extensions.json
.vscode/settings.json
README.md
cspell.json
post-scan-actions/aws-python-promote-or-quarantine/README.md
post-scan-actions/aws-python-promote-or-quarantine/other-installation-methods.md
post-scan-actions/aws-python-promote-or-quarantine/template.yml

- Add SAM template for SAM CLI installation method.
- Renamed `README.md` to `other-installation-methods.md` and add a new README.md for SAR installation.]
> Review changes in different commits may be a lot eaiser.

feat: Add SAM template for promote/quarantine plugin

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

SAR takes every parameter as required. We have to provide default value for optional parameters.

fix: Add parameter default value to fix SAR required parameter

---

post-scan-actions/aws-python-teams-notification/README.md
post-scan-actions/aws-python-teams-notification/handler.py

Hey Team,
Created a MS teams integration for C1-FSS,
I used the Slack integration code as Teams uses web hook similar with Slack.
Also added doc on how to deploy
Thanks,
Justin

feat: Adding integration with microsoft teams and fss

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/new_plugin_request.md
.github/pull_request_template.md

- Add issue templates of
- Bug report
- Feature request
- New plugin request
- Add an PR template

chore: Add issue and PR templates

---

post-scan-actions/aws-python-promote-or-quarantine/README.md

doc: Reflect UI changes, as requested

Updated README.md

---

post-scan-actions/aws-python-teams-notification/handler.py

fix: FSS integration with ms-teams

---

post-scan-actions/aws-python-promote-or-quarantine/handler.py
post-scan-actions/aws-python-promote-or-quarantine/template.yml

fix: Skip promote if scan was failed

---

post-scan-actions/aws-python-promote-or-quarantine/handler.py
post-scan-actions/aws-python-promote-or-quarantine/template.yml

fix: Fix syntax error

---

.gitignore
deployment/aws-terraform/README.md
deployment/aws-terraform/all-in-one/main.tf
deployment/aws-terraform/scanner-stack/main.tf
deployment/aws-terraform/storage-stack/main.tf

Add Terraform templates for FSS AWS stacks deployment

feat: Add Terraform template for FSS aws stacks deployment

---

.github/CONTRIBUTING.md
README.md
post-scan-actions/aws-python-promote-or-quarantine/handler.py
post-scan-actions/aws-python-promote-or-quarantine/template.yml

- Add new tags as post-scan-action-tag
- Updated readme and contributing guide on the way.

feat: Add detail tags to promote-or-quarantine plugin

---

post-scan-actions/aws-python-promote-or-quarantine/handler.py

fixed syntax error on line number 147 and 148

---

post-scan-actions/aws-python-promote-or-quarantine/template.yml

chore: Update version for #58

---

.github/pull_request_template.md
.markdownlint.yml
.markdownlintrc

docs: Add version bumping to PR checklist

---

post-scan-actions/aws-python-promote-or-quarantine/handler.py
post-scan-actions/aws-python-promote-or-quarantine/template.yml
post-scan-actions/azure-python-promote-or-quarantine/promoteOrQuarantineFunction/ScanResultHandler/handler.py

fix: Fix tag message

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.json

Closes #69
- Remove the skip of file size == 0
- Small refactor of resource name postfix generated by CDK.

fix: Don't skip empty file in full scan plugin

---

post-scan-actions/aws-nodejs-securityhub-integration/lambda/package-lock.json
post-scan-actions/aws-nodejs-securityhub-integration/lambda/package.json

fix: Update bestzip

---

post-scan-actions/aws-python-promote-or-quarantine/handler.py
post-scan-actions/aws-python-promote-or-quarantine/template.yml

* Copy valid metadata when copying files
* Apply S3 configuration suggested in the blog post about copying large files
https://aws.amazon.com/tw/blogs/storage/copying-objects-greater-than-5-gb-with-amazon-s3-batch-operations/

feat: Copy metadata and enhance copy for AWS promote quarantine

---

deployment/aws-terraform/all-in-one/main.tf
deployment/aws-terraform/all-in-one/outputs.tf
deployment/aws-terraform/all-in-one/providers.tf
deployment/aws-terraform/all-in-one/variables.tf
deployment/aws-terraform/scanner-stack/main.tf
deployment/aws-terraform/scanner-stack/outputs.tf
deployment/aws-terraform/scanner-stack/providers.tf
deployment/aws-terraform/scanner-stack/variables.tf
deployment/aws-terraform/storage-stack/main.tf
deployment/aws-terraform/storage-stack/outputs.tf
deployment/aws-terraform/storage-stack/providers.tf
deployment/aws-terraform/storage-stack/variables.tf

- Update AWS provider to version `4.27.0`;
- Implement better file structure;
- Add all available variables to the template;
- Add a description to all variables;

feat(deployment): Add quality updates to terraform deployment

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.yaml

fix: Fix the issue that there are sometimes network error when files are re-scanned.

---

scan-triggers/aws-python-bucket-full-and-scheduled-scan/template.yaml

Fix: Fix AWS full scan plugin filter function
